
name: Java CI with Gradle Build
on:
 push:
    branches:
    - '1.30.0-v5.80.0-customisations'
 create:
    tags:
    - 'rc*'
    
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic

jobs:
  build-clouddriver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout clouddriver  repo
      uses: actions/checkout@v3
      #with:
        #repository: opsmx/clouddriver
        #ref: refs/heads/master
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        cache: 'gradle'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Prepare build variables
      id: build_variables
      run: |
          echo ::set-output name=REPO::"ubi8-spin-clouddriver"
          echo ::set-output name=VERSION::"$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')"
    - name: Build
      run: ./gradlew --no-daemon -PenableCrossCompilerPlugin=true clouddriver-web:installDist -x test
    - name: Login to Quay
          #if: startsWith(github.repository, ‘yugaa22/‘)
      uses: docker/login-action@v1
        # use service account flow defined at: https://github.com/docker/login-action#service-account-based-authentication-1
      with:
        registry: ${{ secrets.IMAGE_REPOSITRY }}
        username: ${{ secrets.IMAGE_USERNAME }}
        password: ${{ secrets.IMAGE_PASSWORD }}
    - name: dockerBuildpush
        # Only run this on repositories in the 'spinnaker' org, not on forks.
        #if: startsWith(github.repository, ‘yugaa22/‘)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/ubi8/Dockerfile
        push: true
        tags: |
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}"
    - id: get-build-name
      run: |
            imageName=${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}
            echo "clouddriver=$imageName" >> $GITHUB_OUTPUT
